service: lambda

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
          integration: lambda-proxy
          authorizer: aws_iam
